# Generated by Django 4.1.1 on 2022-09-17 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='E_reg',
            new_name='p_reg',
        ),
    ]
