# Generated by Django 4.1.1 on 2022-09-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_e_reg_p_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_reg',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
