# Generated by Django 4.1.1 on 2022-09-22 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_p_reg_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='p_reg',
            new_name='user',
        ),
    ]
