# Generated by Django 4.1.1 on 2022-10-05 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_subcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='categry',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='category',
            new_name='categry',
        ),
    ]
