# Generated by Django 4.1.1 on 2022-10-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_rename_category_categry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=20)),
                ('f_name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=30)),
                ('cat', models.IntegerField(max_length=30)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
