# Generated by Django 4.1.1 on 2022-10-08 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_user_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='files',
        ),
    ]
