# Generated by Django 4.1.1 on 2022-10-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_rename_proof_expert_filetoupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='fileToUpload',
            field=models.FileField(default='null', upload_to='e_proof/%m'),
            preserve_default=False,
        ),
    ]
