# Generated by Django 4.1.1 on 2022-10-13 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_alter_expert_filetoupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('rating', models.IntegerField(default=1)),
                ('amount', models.IntegerField()),
                ('categry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.categry')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user')),
            ],
        ),
    ]
