# Generated by Django 4.1.1 on 2022-10-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='e_date',
            field=models.DateField(blank=True, null=True, verbose_name='ed'),
        ),
    ]
