# Generated by Django 4.1.1 on 2022-10-18 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_alter_categry_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categry',
            name='cat',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]*$', 'Only uppercase letters and underscores allowed.')]),
        ),
    ]
