# Generated by Django 4.1.1 on 2022-11-18 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_question_expert_question_question_status_pending'),
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1500, unique=True)),
                ('review', models.CharField(max_length=100, unique=True)),
                ('pending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.pending')),
            ],
        ),
    ]
