# Generated by Django 4.1.1 on 2022-11-18 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_answer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='answer',
            new_name='tbl_answer',
        ),
    ]
