# Generated by Django 4.1.1 on 2022-11-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_rename_answer_tbl_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
