# Generated by Django 4.1.1 on 2022-11-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_pending_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_answer',
            name='answer',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_answer',
            name='review',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
