# Generated by Django 4.1.1 on 2022-11-21 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_tbl_answer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='amount',
        ),
    ]
